[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://www.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com; frame-src 'self' https://www.google.com;"

[context.production.environment]
  VITE_FIREBASE_API_KEY = "production-firebase-api-key"
  VITE_FIREBASE_AUTH_DOMAIN = "production-firebase-auth-domain"
  VITE_FIREBASE_PROJECT_ID = "production-firebase-project-id"
  VITE_FIREBASE_STORAGE_BUCKET = "production-firebase-storage-bucket"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "production-firebase-messaging-sender-id"
  VITE_FIREBASE_APP_ID = "production-firebase-app-id"
  VITE_SERVICE_ACCOUNT_JSON = "production-firebase-service-account-json"

[context.deploy-preview.environment]
  VITE_FIREBASE_API_KEY = "preview-firebase-api-key"
  VITE_FIREBASE_AUTH_DOMAIN = "preview-firebase-auth-domain"
  VITE_FIREBASE_PROJECT_ID = "preview-firebase-project-id"
  VITE_FIREBASE_STORAGE_BUCKET = "preview-firebase-storage-bucket"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "preview-firebase-messaging-sender-id"
  VITE_FIREBASE_APP_ID = "preview-firebase-app-id"
  VITE_SERVICE_ACCOUNT_JSON = "preview-firebase-service-account-json"
